### PR TITLE
Add read receipts

### LINKED ISSUE #148: [bluebubbles] Implement SendReadReceipt
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR127

### PR DESCRIPTION
**Pull request by juliettebee**
Fixes #148

### CODE REVIEW

**Comment by cnuss** [comment]
@juliettebee i am adding some helper functions that you can use, standby for a few minutes then you can rebase and use that!

**Comment by cnuss** [comment]
@juliettebee i've merged the helper function to `bluebubbles`, could you please rebase and adopt it? thanks!

**Comment by juliettebee** [comment]
Hoping that fixes the conflict, I don’t know Go the best and I’m doing this while at school so if I need to fix anything I can do it once I get free time.

**Comment by trek-boldly-go** [comment]
@juliettebee I am going to close this because the read receipts should be supported now, but I would be very grateful for more contributions from any of the issues that start with [bluebubbles]. Just set yourself as the assignee so I know to leave that bit of code alone while you work.

**Pull request closed without merging**
